modLoader = "javafml"
loaderVersion = "[${loader_version},)"
license = "${mod_license}"

[[mods]]
modId = "ropebridge"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "https://raw.githubusercontent.com/Cazsius/Rope-Bridge/dev/updates.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/rope-bridge"
logoFile = "../../ropebridge.logo.png"
credits = "Originally created by czechmate777. Art from wiresgal and TrisAstral"
authors = "${mod_authors}"
description = '''
${mod_description}
'''

# Dependencies are optional.
[[dependencies.ropebridge]]
modId = "neoforge"
type = "required"
versionRange = "${neo_range}"
ordering = "NONE" # BEFORE or AFTER required if the relationship is not mandatory
side = "BOTH" # BOTH, CLIENT or SERVER
